#!/bin/env python

"""Generate openvpn-client config from VPN Gate CSV"""

import os
import sys
import configparser
import argparse
from urllib.request import urlopen
from urllib.error import HTTPError, URLError
from codecs import encode, decode
from random import choice, shuffle

from lib.logger import return_logger


class GenerateOpenVPNConfig(object):
    """Generate openvpn-client config from VPN Gate CSV"""

    def __init__(self, conf_name):
        """Constructor: parse config given by conf_name"""

        self.logger = return_logger()

        conf = configparser.ConfigParser(allow_no_value=True)
        if os.path.exists(conf_name):
            conf.read(conf_name)
        else:
            message = "config {conf} doesn't exist".format(
                conf=conf_name)
            self.logger.error(message)
            sys.exit(1)

        self.vpngate_url, self.server_country, self.choice_factor = \
            self.__parse_vpngate_section(conf)
        self.saved_to, http_proxy_host, http_proxy_port = \
            self.__parse_openvpn_section(conf)

        if self.choice_factor == "score":
            self.factor_index = 2
        elif self.choice_factor == "ping":
            self.factor_index = 3
        elif self.choice_factor == "speed":
            self.factor_index = 4
        elif self.choice_factor:
            message = "wrong factor_index: {factor}".format(
                factor=self.choice_factor)
            self.logger.error(message)
            self.logger.error("this must be either 'score', 'ping', 'speed'")
            self.logger.error("ignore your factor_index")

        if None in [http_proxy_host, http_proxy_port]:
            self.http_proxy_dict = None
        else:
            self.http_proxy_dict = {
                "host": http_proxy_host,
                "port": http_proxy_port
                }

    @staticmethod
    def __parse_vpngate_section(conf):
        section_name = "vpngate"
        vpngate_url = conf.get(section_name, "url")
        try:
            server_country = conf.get(section_name, "country")
        except configparser.NoOptionError:
            server_country = None
        try:
            choice_factor = conf.get(section_name, "choice_factor")
        except configparser.NoOptionError:
            choice_factor = None
        return (vpngate_url, server_country, choice_factor)

    @staticmethod
    def __parse_openvpn_section(conf):
        section_name = "openvpn"
        saved_to = conf.get(section_name, "openvpn_client_conf_path")
        try:
            http_proxy_host = conf.get(section_name, "http_proxy_host")
            http_proxy_port = conf.get(section_name, "http_proxy_port")
        except configparser.NoOptionError:
            http_proxy_host = None
            http_proxy_port = None
        return (saved_to, http_proxy_host, http_proxy_port)

    @staticmethod
    def __filter_by_country(server_list, country_code):
        filtered_server_list = []
        for server_info in server_list:
            info_in_list = server_info.split(',')
            country_in_list = info_in_list[6]
            if country_code == country_in_list:
                filtered_server_list.append(server_info)
        return filtered_server_list

    @staticmethod
    def __choose_by_choice_factor(server_list, choice_factor,
                                  factor_index):
        server_dict = {}
        shuffle(server_list)
        for server_info in server_list:
            server_info_list = server_info.split(',')
            if len(server_info_list) > factor_index:
                try:
                    factor = int(server_info_list[factor_index])
                except ValueError:
                    if choice_factor == "ping":
                        factor = sys.maxsize
                    else:
                        factor = -sys.maxsize
                server_dict[factor] = server_info_list
        if choice_factor == "ping":
            factor = min(server_dict.keys())
        else:
            factor = max(server_dict.keys())
        info_in_list = server_dict[factor]
        return info_in_list

    @staticmethod
    def __choose_by_country(server_list, country_code):
        for server_info in server_list:
            if country_code in server_info:
                info_in_list = server_info.split(',')
        return info_in_list

    @staticmethod
    def download_vpngate_csv(url, logger=None):
        """Download VPN Gate server CSV and return it as list."""
        try:
            vpngate = urlopen(url)
        except (HTTPError, URLError) as exception:
            logger.error("got error: {e}".format(
                e=exception))
            sys.exit(1)
        vpngate_csv = vpngate.read()
        server_list = vpngate_csv.decode().split("\r\n")
        return server_list[2:-2]

    def get_openvpn_client_config(self, server_list, logger=None):
        """Get openvpn-client config from given server_list.
        openvpn-client config is filtered by given country (if given)."""
        if self.server_country:
            logger.info("filter openvpn server by country '{c}'".format(
                c=self.server_country))
            server_list = self.__filter_by_country(server_list,
                                                   self.server_country)
            if not server_list:
                logger.error("you specify wrong country code in config")
                logger.error("given country code is '{c}'".format(
                    c=self.server_country))
                sys.exit(1)

        if self.choice_factor:
            logger.info("select openvpn server by {factor}".format(
                factor=self.choice_factor))
            info_in_list = self.__choose_by_choice_factor(
                server_list, self.choice_factor, self.factor_index)
        else:
            logger.info("select openvpn server randomly")
            info_in_str = choice(server_list)
            info_in_list = info_in_str.split(',')

        logger.info("chose {name} in country '{country}'".format(
            name=info_in_list[0],
            country=info_in_list[5]))
        config_in_base64 = encode(info_in_list[-1])
        config_in_raw = decode(config_in_base64, "base64").decode()
        config = '\n'.join(config_in_raw.split("\r\n"))
        return config

    @staticmethod
    def edit_openvpn_client_config(config, http_proxy=None):
        """Edit openvpn-client config.
        if http_proxy is given as dict, replace http proxy info
        in openvpn-client config."""
        additional_config = '\n'.join([
            "script-security 2",
            ("setenv PATH /usr/local/sbin:/usr/local/bin:"
             "/usr/sbin:/usr/bin:/sbin:/bin"),
            "up /etc/openvpn/scripts/update-systemd-resolved",
            "down /etc/openvpn/scripts/update-systemd-resolved",
            "down-pre"
            ])
        config = config + additional_config + '\n'

        if http_proxy:
            config = config.replace(";[proxy server]", http_proxy["host"])
            config = config.replace(";[proxy port]", http_proxy["port"])
            config = config.replace(";http-proxy-retry", "connect-retry-max 1")
        return config

    @staticmethod
    def save_openvpn_client_config(config, conf_location, logger=None):
        """Edit openvpn-client config to given conf_location"""
        with open(conf_location, 'w') as conf_file:
            conf_file.write(config)
        logger.info("openvpn-client config is saved to '{loc}'".format(
            loc=conf_location))

    def generate_conf(self):
        """Run series of tasks below:
            - download csv from VPN Gate
            - choose openvpn server from csv
            - edit openvpn-client config
            - write out openvpn-client config"""
        vpngate_server_list = self.download_vpngate_csv(self.vpngate_url,
                                                        logger=self.logger)
        openvpn_client_conf = self.get_openvpn_client_config(
            vpngate_server_list, logger=self.logger)

        if self.http_proxy_dict:
            openvpn_client_conf = self.edit_openvpn_client_config(
                openvpn_client_conf,
                self.http_proxy_dict)
        else:
            openvpn_client_conf = \
                self.edit_openvpn_client_config(openvpn_client_conf)

        self.save_openvpn_client_config(openvpn_client_conf, self.saved_to,
                                        logger=self.logger)


if __name__ == "__main__":
    PARSER = argparse.ArgumentParser(
        description="Generate openvpn-client config from VPN Gate CSV")
    PARSER.add_argument(
        "--conf",
        metavar="<config>",
        type=str,
        help="Config file")

    ARGS = PARSER.parse_args()
    if ARGS.conf:
        CONFIG_NAME = ARGS.conf
    else:
        SCRIPT_DIR = '/'.join(__file__.split('/')[:-1])
        CONFIG_NAME = os.path.join(SCRIPT_DIR, "files", "config")

    GET_OPENVPN_CLIENT_CONFIG = GenerateOpenVPNConfig(CONFIG_NAME)
    GET_OPENVPN_CLIENT_CONFIG.generate_conf()
